# Document:
# http://simiki.org/docs/configuration.html

url: 
title: richardway's wiki
keywords: 
description: wiki of richard zhang
author: richard zhang
theme: simple2

categories: 
 - name: environment
   label: Environment